"""create initial tables

Revision ID: 21f08e217859
Revises: 
Create Date: 2025-04-05 23:15:26.152525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f08e217859'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offer',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_location', sa.Text(), nullable=False),
    sa.Column('job_experience', sa.Text(), nullable=False),
    sa.Column('job_academic_background', sa.Text(), nullable=False),
    sa.Column('job_number_positions', sa.Integer(), nullable=False),
    sa.Column('job_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('user_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_table('cv',
    sa.Column('cv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_title', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_offer.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cv_id')
    )
    op.create_table('cv_job_matching',
    sa.Column('cv_job_matching_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('matching_score', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.cv_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_offer.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cv_job_matching_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_job_matching')
    op.drop_table('cv')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('job_offer')
    # ### end Alembic commands ###
